### ISSUE TITLE
Problem viewing the Application in Chrome

### ISSUE THREAD

**Issue by securitytube** [securitytube/wifiscanvisualizer#1]
Seems to be an issue viewing the application in Chrome. Anyone with a quick fix / workaround please report on this thread.

**Comment by ashish771** [comment]
We have to use a stable version of chrome browser. App will not work on beta version or developer version of chrome. Choose any stable version of chrome ie: 40.0.2214.115 m (64-bit).  

Please check your chrome browser version:

![1](https://cloud.githubusercontent.com/assets/6920524/6444457/b88cf8e2-c123-11e4-891e-67659b6fa339.jpg)

**Comment by bkovacev** [comment]
What part of the application does not seem to work on Chrome, as I have been testing on Chrome with no issues for now?

**Comment by Ninja-Hakunamatata** [comment]
I have faced this issue, when i was trying to access this application first time using chrome browser.
Everything was worked fine, but i got stuck at "Visualize" section. Once i clicked on Visualize and i got nothing, I mean no text at all about the csv file. But when i have downloaded and installed the stable version of chrome browser so it worked perfectly. Now no problem at all.

Not Worked: 42.0.2311.11 dev-m (64-bit)
Working Version: 40.0.2214.115 m (64-bit)

**Comment by securitytube** [comment]
OK. Here is my analysis. I updated the Flash player but still the issue persists. On closer inspection, I find that both versions of Flash seem to co-exist:

![flash](https://cloud.githubusercontent.com/assets/4024107/6445937/9de496e4-c12d-11e4-8b60-775b696c95b4.PNG)

As soon as I disable the older first one and refresh the player page. Everything works :) try it out and let me know.

**Comment by Ninja-Hakunamatata** [comment]
Finally, It worked in a latest version of chrome browser, which is 42.0.2311.11 dev-m (64-bit). The main problem was Flash player conflict. As we can see in above screenshot. In my system, there are two flash players. So I have completely removed both of them and downloaded the latest one Flash player and it worked perfectly. :smiley: 

![image](https://cloud.githubusercontent.com/assets/6920524/6447202/6cc5048c-c136-11e4-8d97-015d86076cb0.png)

Thanks!!

**Comment by securitytube** [comment]
sounds good! Closing the issue.
