### ISSUE TITLE
Issue with the upload.

### ISSUE THREAD

**Issue by TheodorOdsbu** [securitytube/wifiscanvisualizer#2]
"400 Bad Request
The server could not comply with the request since it is either malformed or otherwise incorrect."
Screenshot: ![uten navn](https://cloud.githubusercontent.com/assets/11274254/6444730/c1fd0ff8-c0ff-11e4-9a6c-789307990d9b.png)

Someone got this too?, I used a plain .cvs file right after the scan.

**Comment by securitytube** [comment]
Could you upload the file online and provide a link here.

**Comment by TheodorOdsbu** [comment]
What do you mean by uploading the file online?
I tried to but, I got the 400 error from the site.

**Comment by securitytube** [comment]
No, I meant please send us the file -  vivek [] securitytube.net  or point us to a link online. Just wanted to check whats wrong.

**Comment by TheodorOdsbu** [comment]
Alright, Here is a link to the .cvs file: http://www.mediafire.com/download/pnak424cqh3amoh/Local-01.csv

**Comment by bkovacev** [comment]
I've managed to upload the given file just fine. Only reason why it would have actually happen is if it you tried uploading it as an xml file.

**Comment by securitytube** [comment]
I was able to do it without any issues?  Here is the shared scan:  http://wifiscanvisualizer.appspot.com/visualize/5256aa47c0f911e4b309a5406faae4de

Also, if you had use the back button for a failed scan, maybe the upload URL might not have been generated properly
