### ISSUE TITLE
Time line chart

### ISSUE THREAD

**Issue by jimbonet** [securitytube/wifiscanvisualizer#3]
More a request than an issue!

Would it be possible to add a timeline chart to represent when AP + clients had been detected(beacons/probes) over a linear time period? The filters could be applied to visualise when clients had associated with an AP or when roaming clients had been detected?

Jim

**Comment by securitytube** [comment]
Hi Jim

This is a good addition but please keep in mind that we are fundamentally limited by the Airodump-NG CSV file. We have the "first seen" column  but this is more of when Airodump detected the association, rather than when it actually happened. 

We will definitely add this to the list of features.

**Comment by jimbonet** [comment]
Good point,  I guess the accuracy is determined by the the frequency of channel hopping too. Also if a client associated with an AP for 10mins, then left for 30mins and then returned and connected for a further 10mins I expect the first seen and last seen would indicate the client had been associated for 50mins. Despite this it would still be a useful addition to the charts data.

Thanks again and keep up the good work.

Jim

**Comment by securitytube** [comment]
Yes, you are correct. The data is not reliable enough to draw microscopic conclusions. 

Good news - we have already started working on this feature! Stay tuned :) should be ready by next week for testing.

**Comment by jimbonet** [comment]
Fantastic! Look forward to trying it out!

**Comment by securitytube** [comment]
Tell me what you think? https://youtu.be/kPMJbX39BfM

**Comment by jimbonet** [comment]
Nice work! How are the x and y axis labelled? Have you thought about adding the feature of selecting an AP and displaying all the associated clients timelines. I was thinking it could be in the format similar to this chart with clients along y axis and time along x axis? http://i.stack.imgur.com/GObfw.png

Are you using Apache flex and flash builder?

**Comment by jimbonet** [comment]
Also would benefit from an oui look up to add vendor/manufacturer column to AP & clients.

**Comment by securitytube** [comment]
Latest version has this feature.
